// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-lbYRzDMQCfAYUniT4ec-jkZ_okUWpW0',
    appId: '1:344874952353:web:20309745abe5f0eab872e0',
    messagingSenderId: '344874952353',
    projectId: 'rasoi-express-bd581',
    authDomain: 'rasoi-express-bd581.firebaseapp.com',
    storageBucket: 'rasoi-express-bd581.firebasestorage.app',
    measurementId: 'G-QX9VFYXNB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYbGwanqOL1k5WFM7PVAygNI9izVgSRE',
    appId: '1:344874952353:android:32726d1215b24048b872e0',
    messagingSenderId: '344874952353',
    projectId: 'rasoi-express-bd581',
    storageBucket: 'rasoi-express-bd581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxSouP0b06RUYtbO5riiOVT3cuwdKNwqQ',
    appId: '1:344874952353:ios:f6dd9f6a452e8986b872e0',
    messagingSenderId: '344874952353',
    projectId: 'rasoi-express-bd581',
    storageBucket: 'rasoi-express-bd581.firebasestorage.app',
    iosClientId: '344874952353-48s7p03pmievdnup7v49f4nvtqierp72.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasoiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxSouP0b06RUYtbO5riiOVT3cuwdKNwqQ',
    appId: '1:344874952353:ios:f6dd9f6a452e8986b872e0',
    messagingSenderId: '344874952353',
    projectId: 'rasoi-express-bd581',
    storageBucket: 'rasoi-express-bd581.firebasestorage.app',
    iosClientId: '344874952353-48s7p03pmievdnup7v49f4nvtqierp72.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasoiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-lbYRzDMQCfAYUniT4ec-jkZ_okUWpW0',
    appId: '1:344874952353:web:6f523e99d8391751b872e0',
    messagingSenderId: '344874952353',
    projectId: 'rasoi-express-bd581',
    authDomain: 'rasoi-express-bd581.firebaseapp.com',
    storageBucket: 'rasoi-express-bd581.firebasestorage.app',
    measurementId: 'G-TVMZL82MTR',
  );

}